DROP TABLE IF EXISTS category;

CREATE TABLE IF NOT EXISTS category
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
    description VARCHAR(255) NOT NULL
) CHARACTER SET = utf8mb4;